### PR TITLE
Silence deprecation warnings for String.strip/1 in Elixir 1.5

### PR DESCRIPTION
**Pull request by whatyouhide**

### CODE REVIEW

**Comment by josevalim** [comment]
Wouldn't a code ensure loaded plus function exported check be cleaner?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
@josevalim maybe yeah. I don't have a strong preference here but to me the version check expresses the intent in a cleaner way (go around deprecation), but if you prefer I can change to `function_exported?`/

**Comment by josevalim** [comment]
I prefer the function exported because we are checking for the functionality and not for the Elixir version.

**Comment by whatyouhide** [comment]
@josevalim okay, pushed an update that uses `function_exported?/1` :).

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
